Rising-Star-DX/contract-ai-partner-backend

- build.gradle
- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/agreement/domain/Agreement.java
- src/main/java/com/partner/contract/agreement/domain/AgreementIncorrectText.java
- src/main/java/com/partner/contract/agreement/domain/CustomText.java
- src/main/java/com/partner/contract/agreement/domain/FileType.java
- src/main/java/com/partner/contract/agreement/domain/MemberAgreement.java
- src/main/java/com/partner/contract/agreement/domain/UploadStatus.java
- src/main/java/com/partner/contract/agreement/repository/AgreementRepository.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/category/controller/CategoryController.java
- src/main/java/com/partner/contract/category/domain/Category.java
- src/main/java/com/partner/contract/category/repository/CategoryRepository.java
- src/main/java/com/partner/contract/category/service/CategoryService.java
- src/main/java/com/partner/contract/member/controller/MemberController.java
- src/main/java/com/partner/contract/member/domain/Company.java
- src/main/java/com/partner/contract/member/domain/Department.java
- src/main/java/com/partner/contract/member/domain/Member.java
- src/main/java/com/partner/contract/member/domain/Role.java
- src/main/java/com/partner/contract/member/repository/MemberRepository.java
- src/main/java/com/partner/contract/member/service/MemberService.java
- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/domain/MemberStandard.java
- src/main/java/com/partner/contract/standard/domain/Standard.java
- src/main/java/com/partner/contract/standard/repository/StandardRepository.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
- src/main/resources/application.yml
chore/architecture-setting -> develop
- 스프링부트 프로젝트 패키지 설계를 진행했습니다.
- MSSQL DML을 기반으로 도메인 코드를 구현했습니다.
- 패키지 구조 및 도메인 코드에 대한 리뷰 부탁드립니다.
> 스프링부트 프로젝트 패키지 및 도메인 코드 설계 (#21)

- src/main/java/com/partner/contract/test/FlaskController.java
feat/test/flask-ocr → develop
- flask 요청과 응답 test 코드 추가
- flask aws url로 변경
- flask api test 코드 및 url 설정에 대한 리뷰 부탁드립니다
> 계약서 저장 및 AI 분석 API 개발 (#19)

- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/agreement/domain/Agreement.java
- src/main/java/com/partner/contract/agreement/dto/AgreementResponseDto.java
- src/main/java/com/partner/contract/agreement/repository/AgreementRepository.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/category/controller/CategoryController.java
- src/main/java/com/partner/contract/category/domain/Category.java
- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/domain/Standard.java
- src/main/java/com/partner/contract/standard/dto/StandardResponseDto.java
- src/main/java/com/partner/contract/standard/repository/StandardRepository.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
- src/main/resources/application.yml
ex) feat/standard/select -> develop
- 기준문서 및 계약서 전체조회 api 구현
- category url 수정 및 getter 어노테이션 추가
- api 구현, dto 구성에 관한 코드리뷰 요청드립니다
> 기준문서 및 계약서 전체조회 api 구현

- src/main/java/com/partner/contract/agreement/common/enums/AiStatus.java
- src/main/java/com/partner/contract/agreement/common/enums/FileStatus.java
- src/main/java/com/partner/contract/agreement/common/enums/FileType.java
- src/main/java/com/partner/contract/agreement/common/enums/Role.java
- src/main/java/com/partner/contract/agreement/domain/Agreement.java
- src/main/java/com/partner/contract/agreement/domain/UploadStatus.java
- src/main/java/com/partner/contract/member/domain/Member.java
- src/main/java/com/partner/contract/standard/domain/Standard.java
ex) fix/status/update-enum -> develop
- AI와 S3 업로드 상태를 분리했습니다.
> AI, File 상태값 분리 (#36)

- src/main/java/com/partner/contract/agreement/domain/Agreement.java
- src/main/java/com/partner/contract/agreement/dto/AgreementListResponseDto.java
- src/main/java/com/partner/contract/common/config/JpaConfig.java
- src/main/java/com/partner/contract/common/enums/AiStatus.java
- src/main/java/com/partner/contract/common/enums/FileStatus.java
- src/main/java/com/partner/contract/common/enums/FileType.java
- src/main/java/com/partner/contract/common/enums/Role.java
- src/main/java/com/partner/contract/common/utils/DocumentStatusUtil.java
- src/main/java/com/partner/contract/global/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/partner/contract/member/domain/Member.java
- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/domain/Standard.java
- src/main/java/com/partner/contract/standard/dto/FileUploadInitRequestDto.java
- src/main/java/com/partner/contract/standard/dto/StandardListResponseDto.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
feat/standard/upload-init -> dev
- 업로드 전 기준문서 고유 번호를 반환하는 API를 개발했습니다.
- 기준문서의 몇 column의 not null -> null 수정에 대해 Domain 코드에 반영되지 못한 부분을 수정하였습니다.
> 업로드 전 기준문서 고유 번호 반환 API 개발

- build.gradle
- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/common/config/AwsS3Config.java
- src/main/java/com/partner/contract/common/dto/FileUploadRequestDto.java
- src/main/java/com/partner/contract/common/service/S3FileUploadService.java
- src/main/java/com/partner/contract/global/exception/error/ErrorCode.java
- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/domain/Standard.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
- src/main/resources/application.yml
ex) feat/standard/upload-file -> dev
- 기준문서 업로드 기능을 개발했습니다.
- S3 설정 추가를 위해 application-secret.yml의 수정이 있습니다. 노션에 첨부해두었습니다.
> 기준문서 업로드 기능 개발

- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/agreement/domain/Agreement.java
- src/main/java/com/partner/contract/agreement/dto/FileUploadInitRequestDto.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
ex) feat/agreement/upload-file -> dev
- 계약서 업로드 기능을 개발했습니다.
> 계약서 업로드 기능 개발

- src/main/java/com/partner/contract/agreement/dto/AgreementListResponseDto.java
- src/main/java/com/partner/contract/agreement/repository/AgreementRepository.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/dto/StandardListResponseDto.java
- src/main/java/com/partner/contract/standard/dto/StandardResponseDto.java
- src/main/java/com/partner/contract/standard/repository/StandardRepository.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
ex) feat/document/select -> develop
- 기준문서/계약서 조회 후 데이터 반환 시 카테고리 이름 추가하였습니다
> 기준문서 / 계약서 조회 시 카테고리 이름 추가 

- src/main/java/com/partner/contract/common/config/RestTemplateConfig.java
- src/main/java/com/partner/contract/common/dto/FlaskResponseDto.java
- src/main/java/com/partner/contract/global/exception/error/ApplicationException.java
- src/main/java/com/partner/contract/global/exception/error/ErrorCode.java
- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
ex) feat/standard/delete -> develop
- 기준문서 삭제 api를 구현하였습니다
- Flask 에러 코드 및 dto를 추가하고, flask에서 넘어오는 에러 코드 전달 처리를 해주었습니다
- 삭제 api 로직 및 에러 코드 처리에 관한 코드리뷰를 요청드립니다
> 기준문서 삭제 api 구현

- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/agreement/repository/AgreementRepository.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/global/exception/error/ErrorCode.java
- src/main/java/com/partner/contract/standard/repository/StandardRepository.java
ex) feat/agreement/delete -> develop
- 계약서 삭제 API 구현
- JPA N+1 문제 해결
- fetch join을 사용하여 JPA N+1 문제를 해결하였습니다
> 계약서 삭제 api 구현

- src/main/java/com/partner/contract/agreement/dto/AgreementListResponseDto.java
- src/main/java/com/partner/contract/category/controller/CategoryController.java
- src/main/java/com/partner/contract/category/dto/CategoryListResponseDto.java
- src/main/java/com/partner/contract/category/repository/CategoryRepository.java
- src/main/java/com/partner/contract/category/service/CategoryService.java
- src/main/java/com/partner/contract/standard/dto/StandardResponseDto.java
ex) feat/category/select -> dev
- 전체 카테고리 api 구현
- 단일 기준 문서 dto에 카테고리명 추가
- 단일 기준문서 dto에 카테고리명이 누락되어 추가했습니다
> 전체 카테고리 api 구현

- src/main/java/com/partner/contract/category/controller/CategoryController.java
- src/main/java/com/partner/contract/category/dto/CategoryListResponseDto.java
- src/main/java/com/partner/contract/category/repository/CategoryRepository.java
- src/main/java/com/partner/contract/category/service/CategoryService.java
ex) feat/category/search -> dev
- 검색 카테고리 api를 구현하였습니다
- 전체 카테고리 조회 쿼리를 수정하였습니다
- 쿼리 및 수정 dto 확인 요청드립니다
> 전체 카테고리 조회 수정 및 검색 카테고리 api 구현

- src/main/java/com/partner/contract/category/controller/CategoryController.java
- src/main/java/com/partner/contract/category/repository/CategoryRepository.java
- src/main/java/com/partner/contract/category/service/CategoryService.java
- src/main/java/com/partner/contract/common/utils/DocumentStatusUtil.java
ex) feat/category/standard-exist -> dev
- 카테고리 기준문서 유무 판단 api를 구현하였습니다
- 파일 상태와 ai 분석 상태가 null일 때, 업로드 중으로 상태 수정하였습니다
- 
> 카테고리 기준문서 유무 판단 api 구현

- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/global/exception/error/ApplicationException.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
ex) feat/standard/error -> dev
- flask 에러코드 처리를 변경하였습니다
-
-
> flask 에러 코드 처리 수정

- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/agreement/repository/AgreementRepository.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/category/controller/CategoryController.java
- src/main/java/com/partner/contract/category/repository/CategoryRepository.java
- src/main/java/com/partner/contract/category/service/CategoryService.java
ex) feat/category/select-merge -> dev
- 카테고리 API 하나로 합쳤습니다
- 계약서 API 하나로 합쳤습니다
- 계약서 API 로직 확인 요청드립니다
> 카테고리 및 계약서 조회 API 하나로 합치기

- src/main/java/com/partner/contract/agreement/repository/AgreementRepository.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/global/exception/error/ErrorCode.java
- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/repository/StandardRepository.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
ex) feat/standard/select-merge -> dev
- 기준문서 조회 API를 하나로 합쳤습니다
- 기준문서 UPLOADING 및 ANALYZING일 때 삭제 안되도록 수정하였습니다
- 
> 기준문서 조회 API 하나로 합치기

- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/global/exception/error/ErrorCode.java
ex) feat/agreement/check-analysis -> dev
- 계약서 AI 분석 여부 확인을 위한 API를 개발했습니다.
- AI Status가 UPLOADING인 경우는 false, SUCCESS/FAILED인 경우에는 true가 반환됩니다.
> 계약서 AI 분석 여부 확인 API 개발

- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/agreement/domain/AgreementIncorrectText.java
- src/main/java/com/partner/contract/agreement/dto/AgreementDetailsResponseDto.java
- src/main/java/com/partner/contract/agreement/dto/IncorrectTextResponseDto.java
- src/main/java/com/partner/contract/agreement/repository/AgreementRepository.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
ex) feat/agreement/details -> dev
- 계약서 교정 문서 조회 API를 개발했습니다.
> 계약서 교정 문서 조회 API 개발

- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
ex) feat/standard/check-analysis -> dev
- 기준문서 AI 분석 여부 확인을 위한 polling 구현
- 계약서 AI 분석 체크 함수와 동일한 기능입니다.
> 기준문서 AI 분석 여부 확인을 위한 polling 구현

- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/agreement/domain/Agreement.java
- src/main/java/com/partner/contract/agreement/domain/AgreementIncorrectText.java
- src/main/java/com/partner/contract/agreement/repository/AgreementIncorrectTextRepository.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/global/exception/error/ErrorCode.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
ex) feat/agreement/analysis-hard -> dev
- 프론트엔드 테스트를 위한 계약서 AI 분석 하드 코딩 구현
- 프론트엔드의 빠른 테스트를 위해 AI 분석 코드를 하드코딩으로 개발했습니다. 
- 실제 분석 환경과 비슷하게 구현하기 위해 5초를 지연시키는 코드를 추가했습니다.
> 프론트엔드 테스트를 위한 계약서 AI 분석 하드코딩 구현

- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/agreement/domain/Agreement.java
- src/main/java/com/partner/contract/agreement/dto/AgreementAnalysisFlaskResponseDto.java
- src/main/java/com/partner/contract/agreement/dto/AgreementIncorrectTextDto.java
- src/main/java/com/partner/contract/agreement/service/AgreementAnalysisAsyncService.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/common/config/AsyncConfig.java
- src/main/java/com/partner/contract/global/exception/error/ErrorCode.java
- src/main/java/com/partner/contract/global/exception/error/SuccessCode.java
- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/service/StandardAnalysisAsyncService.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
- src/main/java/com/partner/contract/test/FlaskController.java
ex) feat/agreement/new-analysis -> dev
- 계약서 AI 분석을 구현했습니다.
- 비동기로 구현하여 클라이언트의 요청이 올 경우 바로 응답을 줍니다. 이후 비동기로 Flask에 분석 요청을 보냅니다.
- 프론트엔드에서의 위배 문장 하이라이팅 방식 변경으로 인해 Position 저장을 위한 DB 구조 변경이 필요할 거 같습니다.
- AI 분석 실패 시 FAILED로 들어가게 하는 작업을 추후 진행해야 합니다.
> 계약서 AI 분석 구현

- src/main/java/com/partner/contract/agreement/domain/AgreementIncorrectPosition.java
- src/main/java/com/partner/contract/agreement/domain/AgreementIncorrectText.java
- src/main/java/com/partner/contract/agreement/dto/AgreementAnalysisFlaskResponseDto.java
- src/main/java/com/partner/contract/agreement/dto/AgreementIncorrectDto.java
- src/main/java/com/partner/contract/agreement/dto/IncorrectPositionResponseDto.java
- src/main/java/com/partner/contract/agreement/dto/IncorrectTextResponseDto.java
- src/main/java/com/partner/contract/agreement/repository/AgreementIncorrectPositionRepository.java
- src/main/java/com/partner/contract/agreement/repository/AgreementRepository.java
- src/main/java/com/partner/contract/agreement/service/AgreementAnalysisAsyncService.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
ex) feat/login -> dev
- 조/항이 여러 페이지에 걸쳐져 있는 경우를 위한 DB 구조 조정 및 API 수정
- 페이지에 걸쳐 chunk가 된 경우를 위해 DB 구조를 수정했습니다.
> 조/항이 여러 페이지에 걸쳐져 있는 경우를 위한 DB 구조 조정 및 API 수정

- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/common/enums/FileType.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
ex) feat/document/excel-converter -> dev
- EXCEL 타입을 추가했습니다 (xls, xlsx)
- 문서 타입별로 PDF 변환 여부를 구분하는 로직을 추가하였습니다
-
> EXCEL -> PDF 변환 작업

- src/main/java/com/partner/contract/category/controller/CategoryController.java
- src/main/java/com/partner/contract/category/dto/CategoryListResponseDto.java
- src/main/java/com/partner/contract/category/dto/CategoryNameListResponseDto.java
- src/main/java/com/partner/contract/category/repository/CategoryRepository.java
- src/main/java/com/partner/contract/category/service/CategoryService.java
ex) feat/category/select-title -> dev
-  category 제목만 조회하는 API를 구현하였습니다
-  DTO 데이터 타입 수정하였습니다
- RDB Int -> BigInt로 변경하였습니다
- 데이터 타입 변경에 따라 카테고리 DTO 데이터 타입도 변경하였습니다
> 카테고리 제목 API 구현

- build.gradle
- src/main/java/com/partner/contract/common/aop/ApiLoggingAspect.java
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
ex) feat/aop/logging -> dev
- 디스코드 slow api & error logging 구현
- 로깅 레벨 WARN 이상의 에러를 디스코드로 로깅합니다. WARN이 너무 많이 발생하면 추후 ERROR로 올릴 예정입니다.
> 디스코드 slow api & error logging 구현

- src/main/java/com/partner/contract/agreement/controller/AgreementController.java
- src/main/java/com/partner/contract/agreement/dto/AgreementListRequestForAndroidDto.java
- src/main/java/com/partner/contract/agreement/repository/AgreementRepository.java
- src/main/java/com/partner/contract/agreement/repository/AgreementRepositoryCustom.java
- src/main/java/com/partner/contract/agreement/repository/AgreementRepositoryImpl.java
- src/main/java/com/partner/contract/agreement/service/AgreementService.java
- src/main/java/com/partner/contract/standard/repository/StandardRepositoryImpl.java
ex) feat/android/agreement-select  -> dev
- 기준문서 조회와 로직 동일합니다
-
- status 필터가 없는 경우 분석완료된 문서만 조회되도록 로직 추가하였습니다
> 안드로이드 계약서 필터/정렬 API 구현

- src/main/java/com/partner/contract/agreement/domain/AgreementIncorrectPosition.java
- src/main/java/com/partner/contract/agreement/dto/IncorrectClauseDataDto.java
- src/main/java/com/partner/contract/agreement/dto/IncorrectTextResponseDto.java
- src/main/java/com/partner/contract/agreement/service/AgreementAnalysisAsyncService.java
ex) feat/agreement/change-domain -> dev
- 계약서 DB 및 도메인에 부분 좌표 추가했습니다
- 계약서 분석 후 부분 좌표 저장하는 로직을 추가하였습니다
- 부분 좌표는 빈 배열로 넘어올 수 있다 하여 null 예외 처리만 해줬습니다
> 계약서 DB 구조 및 도메인 수정

- src/main/java/com/partner/contract/common/enums/FileType.java
- src/main/java/com/partner/contract/common/service/FileConversionService.java
- src/main/java/com/partner/contract/global/exception/error/ErrorCode.java
- src/main/java/com/partner/contract/standard/controller/StandardController.java
- src/main/java/com/partner/contract/standard/domain/StandardContent.java
- src/main/java/com/partner/contract/standard/dto/StandardContentRequestDto.java
- src/main/java/com/partner/contract/standard/dto/StandardContentResponseDto.java
- src/main/java/com/partner/contract/standard/repository/StandardRepository.java
- src/main/java/com/partner/contract/standard/service/StandardService.java
ex) feat/standard/update -> dev
- 기준문서 수정 api 구현하였습니다
- 로직은 다음과 같습니다
```
1. List<String>을 TXT 파일로 변환
2. TXT 파일을 PDF로 변환
3. S3에서 기존 url을 지우고, 새로운 파일로 업로드
4. 기준문서 url과 FileStatus.SUCCESS, AIStatus는 null로 업데이트
5. AI 분석 요청하기
```
> 기준문서 수정 api 구현
